//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cornia.core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cornia.core.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand  code cannot be blank..
        /// </summary>
        internal static string BrandCodeFluentValidation {
            get {
                return ResourceManager.GetString("BrandCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand  Name cannot be blank..
        /// </summary>
        internal static string BrandNameFluentValidation {
            get {
                return ResourceManager.GetString("BrandNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand  Sort cannot be blank..
        /// </summary>
        internal static string BrandSortFluentValidation {
            get {
                return ResourceManager.GetString("BrandSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Language.
        /// </summary>
        internal static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color code cannot be blank..
        /// </summary>
        internal static string ColorCodeFluentValidation {
            get {
                return ResourceManager.GetString("ColorCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Name cannot be blank..
        /// </summary>
        internal static string ColorNameFluentValidation {
            get {
                return ResourceManager.GetString("ColorNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Sort cannot be blank..
        /// </summary>
        internal static string ColorSortFluentValidation {
            get {
                return ResourceManager.GetString("ColorSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaiance certificate Code cannot be blank..
        /// </summary>
        internal static string ComplianceCertificateCodeFluentValidation {
            get {
                return ResourceManager.GetString("ComplianceCertificateCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaince certificate name cannot be blank..
        /// </summary>
        internal static string ComplianceCertificateNameFluentValidation {
            get {
                return ResourceManager.GetString("ComplianceCertificateNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaince certificate sort cannot be blank..
        /// </summary>
        internal static string ComplianceCertificateSortFluentValidation {
            get {
                return ResourceManager.GetString("ComplianceCertificateSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Code cannot be blank..
        /// </summary>
        internal static string ContentCodeFluentValidation {
            get {
                return ResourceManager.GetString("ContentCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content  name cannot be blank..
        /// </summary>
        internal static string ContentNameFluentValidation {
            get {
                return ResourceManager.GetString("ContentNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content  sort cannot be blank..
        /// </summary>
        internal static string ContentSortFluentValidation {
            get {
                return ResourceManager.GetString("ContentSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name cannot be blank.
        /// </summary>
        internal static string CurrencyNameFluentValidation {
            get {
                return ResourceManager.GetString("CurrencyNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Sort cannot be blank..
        /// </summary>
        internal static string CurrencySortFluentValidation {
            get {
                return ResourceManager.GetString("CurrencySortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code cannot be blank.
        /// </summary>
        internal static string CustomerCodeFluentValidation {
            get {
                return ResourceManager.GetString("CustomerCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer currency cannot be blank.
        /// </summary>
        internal static string CustomerCurrencyRefFluentValidation {
            get {
                return ResourceManager.GetString("CustomerCurrencyRefFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name cannot be blank.
        /// </summary>
        internal static string CustomerNameFluentValidation {
            get {
                return ResourceManager.GetString("CustomerNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Sort cannot be blank..
        /// </summary>
        internal static string CustomerSortFluentValidation {
            get {
                return ResourceManager.GetString("CustomerSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee type cannot be blank.
        /// </summary>
        internal static string EmployeeEmployeeTypeFluentValidation {
            get {
                return ResourceManager.GetString("EmployeeEmployeeTypeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name cannot be blank.
        /// </summary>
        internal static string EmployeeNameFluentValidation {
            get {
                return ResourceManager.GetString("EmployeeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee sort cannot be blank.
        /// </summary>
        internal static string EmployeeSortFluentValidation {
            get {
                return ResourceManager.GetString("EmployeeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee type Name cannot be blank.
        /// </summary>
        internal static string EmployeeTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("EmployeeTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee type Sort cannot be blank..
        /// </summary>
        internal static string EmployeeTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("EmployeeTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory code cannot be blank..
        /// </summary>
        internal static string FactoryCodeFluentValidation {
            get {
                return ResourceManager.GetString("FactoryCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory name cannot be blank..
        /// </summary>
        internal static string FactoryNameFluentValidation {
            get {
                return ResourceManager.GetString("FactoryNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory sort cannot be blank..
        /// </summary>
        internal static string FactorySortFluentValidation {
            get {
                return ResourceManager.GetString("FactorySortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender  code cannot be blank.
        /// </summary>
        internal static string GenderCodeFluentValidation {
            get {
                return ResourceManager.GetString("GenderCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender  Name cannot be blank..
        /// </summary>
        internal static string GenderNameFluentValidation {
            get {
                return ResourceManager.GetString("GenderNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender sort cannot be blank..
        /// </summary>
        internal static string GenderSortFluentValidation {
            get {
                return ResourceManager.GetString("GenderSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank.
        /// </summary>
        internal static string GroupCompanyNameFluentValidation {
            get {
                return ResourceManager.GetString("GroupCompanyNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Company.
        /// </summary>
        internal static string GroupCompanyUITitle {
            get {
                return ResourceManager.GetString("GroupCompanyUITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN Number..
        /// </summary>
        internal static string InvalidPIN {
            get {
                return ResourceManager.GetString("InvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type Name cannot be blank.
        /// </summary>
        internal static string MaterialTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("MaterialTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type sort cannot be blank..
        /// </summary>
        internal static string MaterialTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("MaterialTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement type Abbreviation cannot be blank.
        /// </summary>
        internal static string MeasurementTypeAbbreviationFluentValidation {
            get {
                return ResourceManager.GetString("MeasurementTypeAbbreviationFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement type Name cannot be blank.
        /// </summary>
        internal static string MeasurementTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("MeasurementTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement type sort cannot be blank..
        /// </summary>
        internal static string MeasurementTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("MeasurementTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type code cannot be blank.
        /// </summary>
        internal static string MessageTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("MessageTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type Name cannot be blank. .
        /// </summary>
        internal static string MessageTypeNameEmpty {
            get {
                return ResourceManager.GetString("MessageTypeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type Name cannot be blank.
        /// </summary>
        internal static string MessageTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("MessageTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type sort cannot be blank..
        /// </summary>
        internal static string MessageTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("MessageTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status Code cannot be blank..
        /// </summary>
        internal static string OrderStatusCodeFluentValidation {
            get {
                return ResourceManager.GetString("OrderStatusCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status name cannot be blank..
        /// </summary>
        internal static string OrderStatusNameFluentValidation {
            get {
                return ResourceManager.GetString("OrderStatusNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status sort cannot be blank..
        /// </summary>
        internal static string OrderStatusSortFluentValidation {
            get {
                return ResourceManager.GetString("OrderStatusSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OrderTypeCodeEmpty {
            get {
                return ResourceManager.GetString("OrderTypeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order  type code cannot be blank..
        /// </summary>
        internal static string OrderTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("OrderTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type Name cannot be blank.
        /// </summary>
        internal static string OrderTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("OrderTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type sort cannot be blank..
        /// </summary>
        internal static string OrderTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("OrderTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing type code cannot be blank..
        /// </summary>
        internal static string PackingTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("PackingTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing type Name cannot be blank..
        /// </summary>
        internal static string PackingTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("PackingTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing type sort cannot be blank..
        /// </summary>
        internal static string PackingTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("PackingTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type Name cannot be blank..
        /// </summary>
        internal static string PaymentTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("PaymentTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type Sort cannot be blank..
        /// </summary>
        internal static string PaymentTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("PaymentTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name can not be blank..
        /// </summary>
        internal static string PermissionNameFluentValidation {
            get {
                return ResourceManager.GetString("PermissionNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission sort can not be blank..
        /// </summary>
        internal static string PermissionSortFluentValidation {
            get {
                return ResourceManager.GetString("PermissionSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission type Name cannot be blank..
        /// </summary>
        internal static string PermissionTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("PermissionTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Permission type Sort cannot be blank..
        /// </summary>
        internal static string PermissionTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("PermissionTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Name cannot be blank..
        /// </summary>
        internal static string PersonNameFluentValidation {
            get {
                return ResourceManager.GetString("PersonNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Sort cannot be blank..
        /// </summary>
        internal static string PersonSortFluentValidation {
            get {
                return ResourceManager.GetString("PersonSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Surname cannot be blank..
        /// </summary>
        internal static string PersonSurnameFluentValidation {
            get {
                return ResourceManager.GetString("PersonSurnameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Title cannot be blank..
        /// </summary>
        internal static string PersonTitleFluentValidation {
            get {
                return ResourceManager.GetString("PersonTitleFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person type code cannot be blank..
        /// </summary>
        internal static string PersonTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("PersonTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person type cannot be blank..
        /// </summary>
        internal static string PersonTypeFluentValidation {
            get {
                return ResourceManager.GetString("PersonTypeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person type name cannot be blank..
        /// </summary>
        internal static string PersonTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("PersonTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person type sort cannot be blank..
        /// </summary>
        internal static string PersonTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("PersonTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture type code cannot be blank..
        /// </summary>
        internal static string PictureTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("PictureTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture type Name cannot be blank..
        /// </summary>
        internal static string PictureTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("PictureTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture type sort cannot be blank..
        /// </summary>
        internal static string PictureTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("PictureTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production plan type code cannot be blank..
        /// </summary>
        internal static string ProductionPlanTypeCodeFluentValidation {
            get {
                return ResourceManager.GetString("ProductionPlanTypeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production plan type Name cannot be blank..
        /// </summary>
        internal static string ProductionPlanTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("ProductionPlanTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production plan type sort cannot be blank..
        /// </summary>
        internal static string ProductionPlanTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("ProductionPlanTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process alert day cannot be blank..
        /// </summary>
        internal static string ProductionProcessAlertDayFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessAlertDayFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process Code cannot be blank..
        /// </summary>
        internal static string ProductionProcessCodeFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process group Name cannot be blank..
        /// </summary>
        internal static string ProductionProcessGroupNameFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessGroupNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process group sort cannot be blank..
        /// </summary>
        internal static string ProductionProcessGroupSortFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessGroupSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process name cannot be blank..
        /// </summary>
        internal static string ProductionProcessNameFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process sort cannot be blank..
        /// </summary>
        internal static string ProductionProcessSortFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production process Warning day cannot be blank..
        /// </summary>
        internal static string ProductionProcessWarningDayFluentValidation {
            get {
                return ResourceManager.GetString("ProductionProcessWarningDayFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production type Name cannot be blank..
        /// </summary>
        internal static string ProductionTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("ProductionTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production type sort cannot be blank..
        /// </summary>
        internal static string ProductionTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("ProductionTypeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code field empty.
        /// </summary>
        internal static string ResultCodeCodeEmpty {
            get {
                return ResourceManager.GetString("ResultCodeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password can not be empty..
        /// </summary>
        internal static string ResultCodeConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("ResultCodeConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm PINE cannot be blank.
        /// </summary>
        internal static string ResultCodeConfirmPINEmpty {
            get {
                return ResourceManager.GetString("ResultCodeConfirmPINEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data..
        /// </summary>
        internal static string ResultCodeDataNotFound {
            get {
                return ResourceManager.GetString("ResultCodeDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item already exist..
        /// </summary>
        internal static string ResultCodeDuplicate {
            get {
                return ResourceManager.GetString("ResultCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail address..
        /// </summary>
        internal static string ResultCodeEmailAddressIsNull {
            get {
                return ResourceManager.GetString("ResultCodeEmailAddressIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your e-mail &amp; password.
        /// </summary>
        internal static string ResultCodeEmailOrPasswordEmpty {
            get {
                return ResourceManager.GetString("ResultCodeEmailOrPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is not valid.
        /// </summary>
        internal static string ResultCodeInvalidEmail {
            get {
                return ResourceManager.GetString("ResultCodeInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is invalid.
        /// </summary>
        internal static string ResultCodeInvalidOldPassword {
            get {
                return ResourceManager.GetString("ResultCodeInvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old PIN is Invalid.
        /// </summary>
        internal static string ResultCodeInvalidOldPIN {
            get {
                return ResourceManager.GetString("ResultCodeInvalidOldPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not valid.
        /// </summary>
        internal static string ResultCodeInvalidPassword {
            get {
                return ResourceManager.GetString("ResultCodeInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password Format..
        /// </summary>
        internal static string ResultCodeInvalidPasswordFormat {
            get {
                return ResourceManager.GetString("ResultCodeInvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN number.
        /// </summary>
        internal static string ResultCodeInvalidPIN {
            get {
                return ResourceManager.GetString("ResultCodeInvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN Format..
        /// </summary>
        internal static string ResultCodeInvalidPinFormat {
            get {
                return ResourceManager.GetString("ResultCodeInvalidPinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEasurement type Abbreviatin cannot be blank..
        /// </summary>
        internal static string ResultCodeMeasurementTypeAbbreviatinEmptyon {
            get {
                return ResourceManager.GetString("ResultCodeMeasurementTypeAbbreviatinEmptyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement type code cannot be blank.
        /// </summary>
        internal static string ResultCodeMeasurementTypeCodeEmpty {
            get {
                return ResourceManager.GetString("ResultCodeMeasurementTypeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEasurement type Name cannot be blank.
        /// </summary>
        internal static string ResultCodeMeasurementTypeNameEmpty {
            get {
                return ResourceManager.GetString("ResultCodeMeasurementTypeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not exist.
        /// </summary>
        internal static string ResultCodeMemberNotExist {
            get {
                return ResourceManager.GetString("ResultCodeMemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field empty..
        /// </summary>
        internal static string ResultCodeNameEmpty {
            get {
                return ResourceManager.GetString("ResultCodeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Old Password doesn&apos;t match.
        /// </summary>
        internal static string ResultCodeNewAndConfirmPasswordMissmatch {
            get {
                return ResourceManager.GetString("ResultCodeNewAndConfirmPasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PIN and Confirm PIN doesn&apos;t match.
        /// </summary>
        internal static string ResultCodeNewAndConfirmPINMissmatch {
            get {
                return ResourceManager.GetString("ResultCodeNewAndConfirmPINMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password can not be empty..
        /// </summary>
        internal static string ResultCodeNewPasswordEmpty {
            get {
                return ResourceManager.GetString("ResultCodeNewPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PIN cannot be blank.
        /// </summary>
        internal static string ResultCodeNewPINEmpty {
            get {
                return ResourceManager.GetString("ResultCodeNewPINEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have  add access..
        /// </summary>
        internal static string ResultCodeNoAddPermission {
            get {
                return ResourceManager.GetString("ResultCodeNoAddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Delete access..
        /// </summary>
        internal static string ResultCodeNoDeletePermission {
            get {
                return ResourceManager.GetString("ResultCodeNoDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Update access..
        /// </summary>
        internal static string ResultCodeNoUpdatePermission {
            get {
                return ResourceManager.GetString("ResultCodeNoUpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password can not be empty..
        /// </summary>
        internal static string ResultCodeOldPasswordEmpty {
            get {
                return ResourceManager.GetString("ResultCodeOldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PIN cannot be blank.
        /// </summary>
        internal static string ResultCodeOldPINEmpty {
            get {
                return ResourceManager.GetString("ResultCodeOldPINEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your have successfully change your password..
        /// </summary>
        internal static string ResultCodePasswordChangeSuccess {
            get {
                return ResourceManager.GetString("ResultCodePasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field empty..
        /// </summary>
        internal static string ResultCodePasswordEmpty {
            get {
                return ResourceManager.GetString("ResultCodePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission ID already exist..
        /// </summary>
        internal static string ResultCodePermissionIdAlreadyExist {
            get {
                return ResourceManager.GetString("ResultCodePermissionIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name already exist..
        /// </summary>
        internal static string ResultCodePermissionNameAlreadyExist {
            get {
                return ResourceManager.GetString("ResultCodePermissionNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully change your PIN..
        /// </summary>
        internal static string ResultCodePINChangeSuccess {
            get {
                return ResourceManager.GetString("ResultCodePINChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN can not be blank..
        /// </summary>
        internal static string ResultCodePINEmpty {
            get {
                return ResourceManager.GetString("ResultCodePINEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string ResultCodeSuccess {
            get {
                return ResourceManager.GetString("ResultCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist under this customer..
        /// </summary>
        internal static string ResultCodeUserExistUnderThisCustomer {
            get {
                return ResourceManager.GetString("ResultCodeUserExistUnderThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist under this Factory ..
        /// </summary>
        internal static string ResultCodeUserExistUnderThisFactory {
            get {
                return ResourceManager.GetString("ResultCodeUserExistUnderThisFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist under this group.
        /// </summary>
        internal static string ResultCodeUserExistUnderThisGroup {
            get {
                return ResourceManager.GetString("ResultCodeUserExistUnderThisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist under this Person ..
        /// </summary>
        internal static string ResultCodeUserExistUnderThisPerson {
            get {
                return ResourceManager.GetString("ResultCodeUserExistUnderThisPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User type permission already exist into this user type..
        /// </summary>
        internal static string ResultCodeUserTypePermissionExist {
            get {
                return ResourceManager.GetString("ResultCodeUserTypePermissionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Code cannot be blank..
        /// </summary>
        internal static string SeasonCodeFluentValidation {
            get {
                return ResourceManager.GetString("SeasonCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Name cannot be blank..
        /// </summary>
        internal static string SeasonNameFluentValidation {
            get {
                return ResourceManager.GetString("SeasonNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season sort cannot be blank..
        /// </summary>
        internal static string SeasonSortFluentValidation {
            get {
                return ResourceManager.GetString("SeasonSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season year Code cannot be blank..
        /// </summary>
        internal static string SeasonYearCodeFluentValidation {
            get {
                return ResourceManager.GetString("SeasonYearCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season year name cannot be blank..
        /// </summary>
        internal static string SeasonYearNameFluentValidation {
            get {
                return ResourceManager.GetString("SeasonYearNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season year sort cannot be blank..
        /// </summary>
        internal static string SeasonYearSortFluentValidation {
            get {
                return ResourceManager.GetString("SeasonYearSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Value - EN.
        /// </summary>
        internal static string Service_Result_Member_NotFound {
            get {
                return ResourceManager.GetString("Service_Result_Member_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Code cannot be blank..
        /// </summary>
        internal static string SizeCodeFluentValidation {
            get {
                return ResourceManager.GetString("SizeCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size  Name cannot be blank..
        /// </summary>
        internal static string SizeNameFluentValidation {
            get {
                return ResourceManager.GetString("SizeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size sort cannot be blank..
        /// </summary>
        internal static string SizeSortFluentValidation {
            get {
                return ResourceManager.GetString("SizeSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title code cannot be blank..
        /// </summary>
        internal static string TitleCodeFluentValidation {
            get {
                return ResourceManager.GetString("TitleCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title name cannot be blank..
        /// </summary>
        internal static string TitleNameFluentValidation {
            get {
                return ResourceManager.GetString("TitleNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title sort cannot be blank..
        /// </summary>
        internal static string TitleSortFluentValidation {
            get {
                return ResourceManager.GetString("TitleSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code cannot be blank.
        /// </summary>
        internal static string UserCodeFluentValidation {
            get {
                return ResourceManager.GetString("UserCodeFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name cannot be blank.
        /// </summary>
        internal static string UserNameFluentValidation {
            get {
                return ResourceManager.GetString("UserNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sort cannot be blank.
        /// </summary>
        internal static string UserSortFluentValidation {
            get {
                return ResourceManager.GetString("UserSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Name cannot be blank..
        /// </summary>
        internal static string UserTypeNameFluentValidation {
            get {
                return ResourceManager.GetString("UserTypeNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Permission Name cannot be blank..
        /// </summary>
        internal static string UserTypePermissionNameFluentValidation {
            get {
                return ResourceManager.GetString("UserTypePermissionNameFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Permission cannot be blank..
        /// </summary>
        internal static string UserTypePermissionPermissionRefFluentValidation {
            get {
                return ResourceManager.GetString("UserTypePermissionPermissionRefFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Permission Sort cannot be blank..
        /// </summary>
        internal static string UserTypePermissionSortFluentValidation {
            get {
                return ResourceManager.GetString("UserTypePermissionSortFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Permission User type cannot be blank..
        /// </summary>
        internal static string UserTypePermissionUserTypeRefFluentValidation {
            get {
                return ResourceManager.GetString("UserTypePermissionUserTypeRefFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type Sort cannot be blank..
        /// </summary>
        internal static string UserTypeSortFluentValidation {
            get {
                return ResourceManager.GetString("UserTypeSortFluentValidation", resourceCulture);
            }
        }
    }
}
