//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cornia.web.app.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cornia.web.app.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to show in the grid..
        /// </summary>
        public static string Grid_Message_Empty {
            get {
                return ResourceManager.GetString("Grid_Message_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Grid_Operation_Add {
            get {
                return ResourceManager.GetString("Grid_Operation_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_Operation_Delete {
            get {
                return ResourceManager.GetString("Grid_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Grid_Operation_Save {
            get {
                return ResourceManager.GetString("Grid_Operation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Grid_Operation_Update {
            get {
                return ResourceManager.GetString("Grid_Operation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string GridHeader_Active {
            get {
                return ResourceManager.GetString("GridHeader_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string GridHeader_Code {
            get {
                return ResourceManager.GetString("GridHeader_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridHeader_Name {
            get {
                return ResourceManager.GetString("GridHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string GridHeader_Note {
            get {
                return ResourceManager.GetString("GridHeader_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string GridHeader_Sort {
            get {
                return ResourceManager.GetString("GridHeader_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GroupCompany_GridHeader_Address {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        public static string GroupCompany_GridHeader_BankAccounts {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Title.
        /// </summary>
        public static string GroupCompany_GridHeader_CommercialTitle {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_CommercialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string GroupCompany_GridHeader_ContactPerson {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GroupCompany_GridHeader_Description {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string GroupCompany_GridHeader_Email {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone One.
        /// </summary>
        public static string GroupCompany_GridHeader_PhoneOne {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_PhoneOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Two.
        /// </summary>
        public static string GroupCompany_GridHeader_PhoneTwo {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_PhoneTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GroupCompany_GridHeader_User {
            get {
                return ResourceManager.GetString("GroupCompany_GridHeader_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Header_Welcome {
            get {
                return ResourceManager.GetString("Header_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numbers and Letters. Small or Capital Letters are ok. At least one letter / At least one number / Min 5 Max 25 Char long. Repeated letters or numbers are not accepted.
        /// </summary>
        public static string Message_User_Password_Format {
            get {
                return ResourceManager.GetString("Message_User_Password_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numbers and Letters. Small or Capital Letters are ok but not mandatory. Min 4 Max 8 Char long. Repeated letters or numbers are not accepted.
        /// </summary>
        public static string Message_User_PIN_Format {
            get {
                return ResourceManager.GetString("Message_User_PIN_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string ViewTitle_Brand {
            get {
                return ResourceManager.GetString("ViewTitle_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ViewTitle_Color {
            get {
                return ResourceManager.GetString("ViewTitle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Certificate.
        /// </summary>
        public static string ViewTitle_ComplianceCertificate {
            get {
                return ResourceManager.GetString("ViewTitle_ComplianceCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ViewTitle_Configuration {
            get {
                return ResourceManager.GetString("ViewTitle_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ViewTitle_Content {
            get {
                return ResourceManager.GetString("ViewTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string ViewTitle_Currency {
            get {
                return ResourceManager.GetString("ViewTitle_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ViewTitle_Dashboard {
            get {
                return ResourceManager.GetString("ViewTitle_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string ViewTitle_Employee {
            get {
                return ResourceManager.GetString("ViewTitle_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeType.
        /// </summary>
        public static string ViewTitle_EmployeeType {
            get {
                return ResourceManager.GetString("ViewTitle_EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ViewTitle_Gender {
            get {
                return ResourceManager.GetString("ViewTitle_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Company.
        /// </summary>
        public static string ViewTitle_GroupCompany {
            get {
                return ResourceManager.GetString("ViewTitle_GroupCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string ViewTitle_Lock {
            get {
                return ResourceManager.GetString("ViewTitle_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ViewTitle_Login {
            get {
                return ResourceManager.GetString("ViewTitle_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string ViewTitle_MaterialType {
            get {
                return ResourceManager.GetString("ViewTitle_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Type.
        /// </summary>
        public static string ViewTitle_MeasurementType {
            get {
                return ResourceManager.GetString("ViewTitle_MeasurementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        public static string ViewTitle_MessageType {
            get {
                return ResourceManager.GetString("ViewTitle_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ViewTitle_Profile {
            get {
                return ResourceManager.GetString("ViewTitle_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Year.
        /// </summary>
        public static string ViewTitle_SeasonYear {
            get {
                return ResourceManager.GetString("ViewTitle_SeasonYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ViewTitle_Size {
            get {
                return ResourceManager.GetString("ViewTitle_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ViewTitle_Title {
            get {
                return ResourceManager.GetString("ViewTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Undefined.
        /// </summary>
        public static string ViewTitle_Undefined {
            get {
                return ResourceManager.GetString("ViewTitle_Undefined", resourceCulture);
            }
        }
    }
}
