//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cornia.core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypePermission
    {
        public int Id { get; set; }
        public int UserTypeRef { get; set; }
        public int PermissionRef { get; set; }
        public int Denied { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
